name: Auto Update

on: [issues]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          venv\Scripts\python -m pip install --upgrade pip wheel setuptools
          venv\Scripts\python -m pip install aiohttp pillow pypinyin
          
      - name: Run
        env:
          SERVER: ${{ secrets.SERVER }}
          KEY: ${{ secrets.KEY }}
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\python update_arknights.py
